# Generated by Django 4.1.1 on 2023-03-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=30)),
                ('fromadd', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('fno', models.IntegerField()),
                ('usercode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('usercode', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=10)),
            ],
        ),
    ]
