# Generated by Django 4.1.1 on 2023-03-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogins',
            name='drsno',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlogins',
            name='lrno',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlogins',
            name='manifestno',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
