# Generated by Django 4.1.1 on 2023-03-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_userlogins_drsno_userlogins_lrno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogins',
            old_name='usercode',
            new_name='areacode',
        ),
    ]
