# Generated by Django 4.1.1 on 2023-03-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogins',
            name='officeadd',
            field=models.CharField(default=' ', max_length=60),
            preserve_default=False,
        ),
    ]
