# Generated by Django 4.1.1 on 2023-03-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('date', models.DateField()),
                ('type', models.CharField(max_length=6)),
                ('fromadd', models.CharField(max_length=100)),
                ('toadd', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('toname', models.CharField(max_length=100)),
                ('fno', models.IntegerField()),
                ('tono', models.IntegerField()),
                ('pcs', models.IntegerField()),
                ('wt', models.DecimalField(decimal_places=3, max_digits=5)),
                ('invoiceno', models.IntegerField()),
                ('invoiceamt', models.DecimalField(decimal_places=3, max_digits=5)),
                ('charges', models.DecimalField(decimal_places=3, max_digits=5)),
                ('freightcharges', models.DecimalField(decimal_places=3, max_digits=5)),
                ('lrcharges', models.DecimalField(decimal_places=3, max_digits=5)),
                ('door_delivery_charges', models.DecimalField(decimal_places=3, max_digits=5)),
                ('others_charges', models.DecimalField(decimal_places=3, max_digits=5)),
                ('total_charges', models.DecimalField(decimal_places=3, max_digits=5)),
                ('uid', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
