# Generated by Django 4.1.1 on 2023-03-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_uid_booking_lrno_booking_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='charges',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='door_delivery_charges',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='freightcharges',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='invoiceamt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='lrcharges',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='others_charges',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_charges',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='wt',
            field=models.IntegerField(),
        ),
    ]
