# Generated by Django 4.1.1 on 2023-03-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ewaybillno',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
    ]
